---
- name: Gather facts
  hosts: all
  gather_facts: true
  tasks:
    - name: Set default policy for chain
      iptables:
        chain: OUTPUT
        policy: ACCEPT

    - name: Allow traffic from local net 10.253.155.0/24
      iptables:
        comment: "Allow traffic from local network 10.253.155.0/24"
        action: insert
        chain: OUTPUT
        destination: 10.253.155.0/24
        jump: ACCEPT
        state: absent

    - name: Allow traffic for SSH
      iptables:
        comment: "Allow accept for SSH connention"
        action: insert
        chain: OUTPUT
        source_port: "22"
        protocol: tcp
        jump: ACCEPT
        state: absent

