---
- name: First play
  hosts: all
  roles:
    - role_1
    - role_2

  tasks:
    - name: First task
      debug:
        msg: |
          this is first task

    - name: Second task
      debug:
        msg: |
          this is {{ item }} task
      with_items:
        - second
        - third
        - fourth
