---
- name: Test ansible
  hosts: all
  gather_facts: false
  roles:
    - nomad-host-volumes

- name: Test ansible
  hosts: all
  gather_facts: false
  tasks:
    - debug:
        msg: |
          {{ host_volumes | to_nice_yaml }}