---

- file:
    path: /tmp/ansible.log
    state: absent

- name: Do copy images
  # include_tasks: do_copy.yml
  shell: sleep {{ network_speed }} && touch /tmp/{{ copy_item }} && echo "copied {{ copy_item }}..." >>/tmp/ansible.log
  async: 100
  poll: 0
  register: async_tasks
  loop_control:
    loop_var: copy_item
  loop:
    - test_1
    - test_2
    - test_3
    - test_4
    - test_5
    - test_6
    - test_7
    - test_8
    - test_9
    - test_10

- name: verify async copy
  include_tasks: verify_copy_tasks.yml
  loop_control:
    loop_var: task_item
  loop: "{{ async_tasks.results }}"
