# BEGIN NOMAD HOST VOLUMES
host_volumes:
  - name: es-hot-data-02
    path: /mnt/es-ssd-01
  - name: es-hot-data-03
    path: /mnt/es-ssd-02
  - name: es-warm-data-02
    path: /mnt/es-hdd-01
  - name: es-warm-data-03
    path: /mnt/es-hdd-02
# END NOMAD HOST VOLUMES