# BEGIN NOMAD HOST VOLUMES
host_volumes:
  - name: telegraf-data-01
    path: /mnt/telegraf-data
  - name: siem-api-data-01
    path: /mnt/siem-api-data
  - name: telegraf-libs
    path: /mnt/telegraf-libs
  - name: kafka-log
    path: /mnt/kafka-data/log
  - name: kafka-datalog-02
    path: /mnt/kafka-data/datalog
# END NOMAD HOST VOLUMES